---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "spring-warehouse-app-config-eynj"
  namespace: "default"
  labels:
    app: "spring-warehouse-app"
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://10.153.128.3:5432/warehouse_db"
  SPRING_DATASOURCE_USERNAME: "warehouse_user"
  SPRING_DATASOURCE_PASSWORD: "warehouse_user_password"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "spring-warehouse-app"
  namespace: "default"
  labels:
    app: "spring-warehouse-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "spring-warehouse-app"
  template:
    metadata:
      labels:
        app: "spring-warehouse-app"
        version: "1.0.3"
    spec:
      containers:
        - name: "app-sha256-1"
          image: "gcr.io/spring-warehouse/app:latest"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: "SPRING_DATASOURCE_URL"
              valueFrom:
                configMapKeyRef:
                  key: "SPRING_DATASOURCE_URL"
                  name: "spring-warehouse-app-config-eynj"
            - name: "SPRING_DATASOURCE_USERNAME"
              valueFrom:
                configMapKeyRef:
                  key: "SPRING_DATASOURCE_USERNAME"
                  name: "spring-warehouse-app-config-eynj"
            - name: "SPRING_DATASOURCE_PASSWORD"
              valueFrom:
                configMapKeyRef:
                  key: "SPRING_DATASOURCE_PASSWORD"
                  name: "spring-warehouse-app-config-eynj"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "spring-warehouse-app-hpa-yybr"
  namespace: "default"
  labels:
    app: "spring-warehouse-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "spring-warehouse-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "spring-warehouse-lb"
  namespace: "default"
  labels:
    app: "spring-warehouse-app"
spec:
  ports:
    - name: "80-to-8080-tcp"
      protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: "spring-warehouse-app"
  type: "LoadBalancer"
  loadBalancerIP: ""

