name: Build & Test code on push to master
on:
  push:
    branches:
      - master

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and test
        run: ./gradlew clean build test jacocoTestCoverageVerification

      - name: Upload JaCoCo coverage report
        if: success()
        run: |
          export CODACY_PROJECT_TOKEN=${{secrets.CODACY_API_KEY}}
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r app/build/reports/jacoco/test/jacocoTestReport.xml